# Generated by Django 5.1.1 on 2024-10-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_remove_donation_amount_remove_donation_donation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='bank_account',
            field=models.CharField(help_text="Enter the church's bank account details", max_length=100),
        ),
    ]
