# Generated by Django 5.1.1 on 2024-10-09 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_alter_donation_bank_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='city',
            new_name='location',
        ),
    ]
