# Generated by Django 5.1.1 on 2024-10-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_rename_city_branch_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Devotional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bible_portion', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
