# Generated by Django 5.1.1 on 2024-10-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0009_alter_blogpost_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='image',
            new_name='poster',
        ),
    ]
