# Generated by Django 5.1.1 on 2024-11-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0011_generaloverseermessage_sermon'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
