# Generated by Django 5.1.1 on 2024-11-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0012_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
