# Generated by Django 5.1.1 on 2024-11-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0014_sermon_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaloverseermessage',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
