# Generated by Django 5.1.1 on 2024-11-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0015_alter_generaloverseermessage_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='date_preached',
            field=models.DateField(),
        ),
    ]
